# Generated by Django 2.2.2 on 2019-08-04 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='')),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=200)),
                ('nascimento', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('RS', 'Rio Grande Do Sul'), ('SC', 'Santa Catarina'), ('PR', 'Parana')], max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=7)),
                ('valor', models.FloatField()),
                ('categoria', models.CharField(choices=[('Cr', 'Carro'), ('Mo', 'Motocicleta'), ('Cn', 'Caaminhão')], max_length=2)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Receber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma', models.CharField(choices=[('PIC', 'PicPay'), ('PAY', 'PayPal')], max_length=3)),
                ('link', models.CharField(max_length=500)),
                ('qrcode', models.ImageField(upload_to='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.Usuario')),
            ],
        ),
    ]
