# Generated by Django 2.2.4 on 2019-08-13 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('rua', models.CharField(max_length=100)),
                ('complemento', models.CharField(default='.', max_length=50)),
                ('valor', models.FloatField()),
                ('ativo', models.BooleanField(default=True)),
                ('alugado', models.BooleanField(default=False)),
                ('categoria', models.CharField(max_length=2)),
                ('modo', models.CharField(max_length=1)),
                ('abre', models.CharField(max_length=5)),
                ('fecha', models.CharField(max_length=5)),
                ('foto', models.ImageField(blank=True, default='imagens/sem_foto.jpg', upload_to='vagas')),
                ('segunda', models.BooleanField(default=False)),
                ('terca', models.BooleanField(default=False)),
                ('quarta', models.BooleanField(default=False)),
                ('quinta', models.BooleanField(default=False)),
                ('sexta', models.BooleanField(default=False)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0)),
                ('avaliacao', models.IntegerField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('endereco', models.CharField(default='', max_length=100)),
                ('alugador', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='alugador', to=settings.AUTH_USER_MODEL)),
                ('locatario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='locatario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, default='imagens/sem_foto.jpg', upload_to='usuarios')),
                ('saldo', models.FloatField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
