# Generated by Django 2.2.4 on 2019-08-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='valor',
        ),
    ]
