# Generated by Django 2.2.4 on 2019-10-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='observacao',
            field=models.CharField(default='', max_length=500),
        ),
    ]
