# Generated by Django 2.2.4 on 2019-10-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_vagas_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='lat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='lng',
            field=models.CharField(max_length=100),
        ),
    ]
