# Generated by Django 2.2.4 on 2019-08-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_remove_transacao_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
