# Generated by Django 2.2.2 on 2019-08-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0004_auto_20190806_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='alugado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vagas',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vagas',
            name='domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vagas',
            name='quarta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vagas',
            name='quinta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vagas',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vagas',
            name='segunda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vagas',
            name='sexta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vagas',
            name='terca',
            field=models.BooleanField(default=False),
        ),
    ]
