# Generated by Django 2.2.4 on 2019-08-14 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0004_auto_20190813_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='vaga',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='painel.Vagas'),
        ),
    ]
