# Generated by Django 2.2.2 on 2019-08-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0005_auto_20190807_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='foto',
            field=models.ImageField(blank=True, default='imagens/sem_foto.jpg', upload_to='imagens'),
        ),
    ]
