# Generated by Django 2.2.4 on 2019-08-14 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0005_transacao_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.Vagas'),
        ),
    ]
