# Generated by Django 2.2.4 on 2019-10-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0005_reservas_reembolsado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagem',
            field=models.ImageField(blank=True, default='sem_foto.jpg', upload_to='usuarios'),
        ),
    ]
