# Generated by Django 2.2.4 on 2019-08-15 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0006_auto_20190813_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='alugadoAte',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
