# Generated by Django 2.2.2 on 2019-08-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0006_vagas_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagem',
            field=models.ImageField(blank=True, default='imagens/sem_foto.jpg', upload_to='usuarios'),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='foto',
            field=models.ImageField(blank=True, default='imagens/sem_foto.jpg', upload_to='vagas'),
        ),
    ]
