# Generated by Django 2.2.4 on 2019-08-16 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('painel', '0007_vagas_alugadoate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('horaEntrada', models.DateTimeField()),
                ('horaSaida', models.DateTimeField()),
                ('alugador', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='alugadorReserva', to=settings.AUTH_USER_MODEL)),
                ('locatario', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='locatarioReserva', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.Vagas')),
            ],
        ),
    ]
