# Generated by Django 2.2.4 on 2019-10-30 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0007_auto_20191030_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='vagas',
            name='avaliacao',
        ),
    ]
