# Generated by Django 2.2.4 on 2019-11-01 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0008_auto_20191030_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='vaga',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='painel.Vagas'),
        ),
    ]
