# Generated by Django 2.2.4 on 2019-08-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0008_reservas'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='latlng',
            field=models.CharField(default='{lat: -27.3667, lng: -53.4}', max_length=100),
        ),
    ]
