# Generated by Django 2.2.4 on 2019-08-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0009_vagas_latlng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagas',
            name='latlng',
        ),
        migrations.AddField(
            model_name='vagas',
            name='lat',
            field=models.CharField(default='-27.3667', max_length=100),
        ),
        migrations.AddField(
            model_name='vagas',
            name='lng',
            field=models.CharField(default='-53.000', max_length=100),
        ),
    ]
