# Generated by Django 2.2.4 on 2019-08-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0010_auto_20190816_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='data',
        ),
        migrations.RemoveField(
            model_name='reservas',
            name='locatario',
        ),
        migrations.RemoveField(
            model_name='transacao',
            name='locatario',
        ),
        migrations.AlterField(
            model_name='vagas',
            name='abre',
            field=models.TimeField(max_length=5),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='fecha',
            field=models.TimeField(max_length=5),
        ),
    ]
