# Generated by Django 2.2.4 on 2019-08-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0011_auto_20190827_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
