# Generated by Django 2.2.4 on 2019-08-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0012_reservas_finalizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='finalizada',
        ),
        migrations.RemoveField(
            model_name='vagas',
            name='alugado',
        ),
        migrations.RemoveField(
            model_name='vagas',
            name='alugadoAte',
        ),
        migrations.RemoveField(
            model_name='vagas',
            name='categoria',
        ),
    ]
