# Generated by Django 2.2.4 on 2019-09-06 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0013_auto_20190828_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, default='imagens/sem_foto.jpg', upload_to='vagas')),
                ('descricao', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='vagas',
            name='foto',
        ),
        migrations.DeleteModel(
            name='Transacao',
        ),
        migrations.AddField(
            model_name='foto',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.Vagas'),
        ),
    ]
