# Generated by Django 2.2.4 on 2019-09-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0014_auto_20190905_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='avaliacaoDono',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='reservas',
            name='avaliacaolocador',
            field=models.IntegerField(default=-1),
        ),
    ]
