# Generated by Django 2.2.4 on 2019-09-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0015_auto_20190905_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='avaliacao',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='vagas',
            name='avaliacao',
            field=models.IntegerField(default=-1),
        ),
    ]
